### ISSUE TITLE
Adding to fabric server does not work. (at least for me)

### ISSUE THREAD

**Issue by NuzzasKatla** [Aizistral-Studios/No-Chat-Reports#114]
I have tried adding the NCR mod to the server's mod folder, got this on start:'

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'No Chat Reports' (nochatreports) 1.19.1-v1.7.1 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
```
The server is a normal fabric server, started with the fabric-server-launch.jar and all

Also here is latest.log
```
[18:52:05] [main/INFO]: Loading Minecraft 1.19.1 with Fabric Loader 0.14.8
[18:52:06] [main/WARN]: Mod resolution failed
[18:52:06] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE nochatreports 1.19.1-v1.7.1 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE nochatreports 1.19.1-v1.7.1]
[18:52:06] [main/INFO]: Reason: [HARD_DEP nochatreports 1.19.1-v1.7.1 {depends fabric @ [*]}]
[18:52:06] [main/INFO]: Fix: add [add:fabric 1 ([(-?,?)])], remove [], replace []
[18:52:06] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'No Chat Reports' (nochatreports) 1.19.1-v1.7.1 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
```
Thank you for any help

**Comment by Aizistral** [comment]
You need to install Fabric API: https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by NuzzasKatla** [comment]
Thank you :)

**Comment by Immabed** [comment]
You really need to mention the Fabric API requirement somewhere on the curseforge page.

And in my experience, when fabric throws a dependency issue in the log, it usually specifies what the dependency is. I thought I had some issue with fabric itself because the dependency is just "any version of fabric" in the log. That is an actual issue that should be addressed.

For instance, I had another unmet dependency today, and it specified the dependency properly:
```
Unmet dependency listing:
	 - Mod 'Inventory Profiles Next' (inventoryprofilesnext) 1.6.1 requires version 1.6.0+kotlin.1.5.0 or later of fabric-language-kotlin, which is missing!
```
