### ISSUE TITLE
Internal connection error when sending any chat message (even a command) on MineHut

### ISSUE THREAD

**Issue by LoganDark** [Aizistral-Studios/No-Chat-Reports#129]
### Modloader

Fabric

### Minecraft Version

1.19.1

### Modloader Version

Fabric Loader 0.4.8 + Fabric API 0.58.5+1.19.1

### No Chat Reports Version

FABRIC-1.19.1-v1.8.2

### Modpack Info

Custom MultiMC (but more info is below)

### The latest.log File

I don't think the full log is important because everything else is perfectly fine (yes - I did search it myself for any logs from No Chat Reports, and there's nothing - no other errors either).

### Bug Description

Whenever I try to send any chat message, I get this error: (this is from a real intermediary client, but is remapped for your convenience)

```
[07:11:44] [Render thread/ERROR]: Failed to retrieve publicKey property for profile e880afbb-7c18-4677-894c-ce41b52204ea
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.network.encryption.PlayerPublicKey.verifyAndDecode(PlayerPublicKey.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.client.network.PlayerListEntry.<init>(PlayerListEntry.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onPlayerList(ClientPlayNetworkHandler.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.PlayerListS2CPacket.apply(PlayerListS2CPacket.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.PlayerListS2CPacket.apply(PlayerListS2CPacket.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) [client-intermediary.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) [client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116) [client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1128) [client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[07:11:44] [Render thread/INFO]: Loaded 4 advancements
[07:11:44] [Render thread/ERROR]: Failed to retrieve publicKey property for profile 3e9ecda5-9ed8-4996-850f-0a2c1e155b34
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.network.encryption.PlayerPublicKey.verifyAndDecode(PlayerPublicKey.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.client.network.PlayerListEntry.<init>(PlayerListEntry.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onPlayerList(ClientPlayNetworkHandler.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.PlayerListS2CPacket.apply(PlayerListS2CPacket.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.PlayerListS2CPacket.apply(PlayerListS2CPacket.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) [client-intermediary.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) [client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116) [client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1128) [client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[07:11:45] [Render thread/INFO]: Saving
[07:11:45] [Render thread/INFO]: Saved in 54 milliseconds.
[07:11:45] [Render thread/INFO]: Stopping worker threads
```

<details><summary>Non-remapped crash report</summary>

```
[07:11:44] [Render thread/ERROR]: Failed to retrieve publicKey property for profile e880afbb-7c18-4677-894c-ce41b52204ea
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[07:11:44] [Render thread/INFO]: Loaded 4 advancements
[07:11:44] [Render thread/ERROR]: Failed to retrieve publicKey property for profile 3e9ecda5-9ed8-4996-850f-0a2c1e155b34
com.mojang.authlib.minecraft.InsecurePublicKeyException$InvalidException: Invalid profile public key signature
	at net.minecraft.class_7428.method_43550(class_7428.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_640.<init>(class_640.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11113(class_634.java:1622) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11721(class_2703.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2703.method_11054(class_2703.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1128) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:767) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[07:11:45] [Render thread/INFO]: Saving
[07:11:45] [Render thread/INFO]: Saved in 54 milliseconds.
[07:11:45] [Render thread/INFO]: Stopping worker threads
```

</details>

### Steps to Reproduce

1. Join `mc.minehut.com` using 1.19.1 with Multiconnect and ViaFabric
2. Try to send any chat message or command
3. You will get kicked with an internal connection error and that message will be logged to console

### Other Information

```
    Directory: C:\Users\LoganDark\Downloads\MultiMC\instances\1.18.2 (2)\.minecraft\mods


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          8/1/2022   6:52 AM          45812 antighost-1.19.1-fabric0.58.5-1.1.5.jar
-a----          8/1/2022   6:52 AM         776264 bobby-4.0.0.jar
-a----          8/1/2022   7:02 AM        1129049 cloth-config-8.0.75-fabric.jar
-a----          8/1/2022   6:53 AM        5887939 dashloader-4.0.0+1.19.jar
-a----          8/1/2022   6:53 AM          89446 dynamic-fps-2.2.0.jar
-a----          8/1/2022   6:53 AM        1498297 fabric-api-0.58.5+1.19.1.jar
-a----          8/1/2022   6:53 AM          38539 fabrishot-1.8.0.jar
-a----          8/1/2022   6:54 AM         119108 ferritecore-5.0.0-fabric.jar
-a----          8/1/2022   6:54 AM         115780 forcecloseloadingscreen-1.1.1.jar
-a----          8/1/2022   6:54 AM         118075 indium-1.0.6+mc1.19.jar
-a----          8/1/2022   6:54 AM        1574252 iris-mc1.19.1-1.2.6.jar
-a----          8/1/2022   7:07 AM         175000 krypton-0.2.1.jar
-a----          8/1/2022   6:55 AM          14531 lazydfu-0.1.3.jar
-a----          8/1/2022   7:05 AM         754418 libjf-2.9.2.jar
-a----          8/1/2022   6:55 AM         445959 modmenu-4.0.5.jar
-a----          8/1/2022   6:55 AM         960530 mousewheelie-1.10.2+mc1.19-pre1.jar
-a----          8/1/2022   6:57 AM        9863928 multiconnect-1.6-beta.21.jar
-a----          8/1/2022   7:08 AM          88064 NoChatReports-FABRIC-1.19.1-v1.8.2.jar
-a----          8/1/2022   6:56 AM          13271 Slyde-1.6.1.jar
-a----          8/1/2022   6:56 AM        1364166 sodium-fabric-mc1.19-0.4.2+build.16.jar
-a----          8/1/2022   6:56 AM         127465 starlight-1.1.1+fabric.ae22326.jar
-a----          8/1/2022   6:58 AM        5793825 viafabric-0.4.8+13-main.jar
```

Mod list with Modrinth links (except for Cloth Config because shedaniel is a money demanding jerk):

[AntiGhost 1.19.1](https://modrinth.com/mod/antighost/version/1.19.1-fabric0.58.5-1.1.5)  
[Bobby 4.0.0](https://modrinth.com/mod/bobby/version/4.0.0)  
[Cloth Config 8.0.75](https://www.curseforge.com/minecraft/mc-mods/cloth-config/download/3906387)  
[Dashloader 4.0.0+1.19](https://modrinth.com/mod/dashloader/version/4.0.0%2B1.19)  
[Dynamic FPS 2.2.0](https://modrinth.com/mod/dynamic-fps/version/2.2.0)  
[Fabric API 0.58.5+1.19.1](https://modrinth.com/mod/fabric-api/version/0.58.5%2B1.19.1)  
[Fabrishot 1.8.0](https://modrinth.com/mod/fabrishot/version/1.8.0)  
[FerriteCore 5.0.0-fabric](https://modrinth.com/mod/ferrite-core/version/5.0.0-fabric)  
[Kennytv's Epic Force Close Loading Screen Mod For Fabric 1.1.1](https://modrinth.com/mod/forcecloseworldloadingscreen/version/1.1.1)  
[Indium 1.0.6+mc1.19](https://modrinth.com/mod/indium/version/1.0.6%2Bmc1.19)  
[Iris 1.19.1-v1.2.6](https://modrinth.com/mod/iris/version/1.19.x-v1.2.6)  
[Krypton 0.2.1](https://modrinth.com/mod/krypton/version/0.2.1)  
[LazyDFU 0.1.3](https://modrinth.com/mod/lazydfu/version/0.1.3)  
[LibJF 2.9.2](https://modrinth.com/mod/libjf/version/2.9.2)  
[ModMenu 4.0.5](https://modrinth.com/mod/modmenu/version/4.0.5)  
[Mouse Wheelie 1.10.2](https://modrinth.com/mod/mouse-wheelie/version/1.10.2%2Bmc1.19-pre1)  
[Multiconnect 1.6-beta.21](https://modrinth.com/mod/multiconnect/version/1.6-beta.21)  
No Chat Reports 1.19.1-v1.8.2  
[Slyde 1.6.1](https://modrinth.com/mod/slyde/version/1.6.1)  
[Sodium mc1.19-0.4.2](https://modrinth.com/mod/sodium/version/mc1.19-0.4.2)  
[Starlight 1.1.1](https://modrinth.com/mod/starlight/version/1.1.1%2B1.19)  
[ViaFabric 0.4.8+13-main](https://modrinth.com/mod/viafabric/version/0.4.8%2B13-main)

I don't think you'll have to worry about installing every single one of these.

**Comment by LoganDark** [comment]
This happens consistently and instantly with the same two UUIDs every time I attempt to use the chat, so it's not some nondeterministic thing with receiving chat messages from other players or anything. At least it doesn't seem like that.

But I can do everything else perfectly fine including receiving messages. Just can't run commands or chat.

**Comment by LoganDark** [comment]
I looked into this myself and discovered two things:

- The errors ~~that No Chat Reports throws~~ in console can be easily fixed but do not cause the problem
- Uninstalling No Chat Reports completely does not fix the problem
- The errors still show up without No Chat Reports

Whoops.

I can open a PR with the fix for the console messages if needed.

**Comment by MODKILLER1001** [comment]
@LoganDark is it similar to this 
![image](https://user-images.githubusercontent.com/17520451/182252198-66a2d8d9-9b88-4ff3-986c-a3193cf1fc86.png)

**Comment by MODKILLER1001** [comment]
Disabling chat preview on your client side completely fixes it for now.

**Comment by LoganDark** [comment]
Disabling chat preview doesn't fix the connection error on my side unfortunately

**Comment by MODKILLER1001** [comment]
This seems to be a issue with multiconnect. Try disabling multiconnect.

**Comment by LoganDark** [comment]
> This seems to be a issue with multiconnect. Try disabling multiconnect.

Thanks, but the server doesn't support 1.19.1, only 1.19. I have already reported this issue: https://github.com/Earthcomputer/multiconnect/issues/448

**Comment by LoganDark** [comment]
OK, with ViaFabric and Multiconnect uninstalled, and with MineHut now supporting 1.19.1 directly, I can actually confirm that No Chat Reports is the culprit here. Installed = error on chatting. Uninstalled = no error on chatting... but I'm not OK with chat reports, so I can't play with No Chat Reports disabled.

Reopening

**Comment by LoganDark** [comment]
This may be a server-side disconnect. Real 1.18.2 clients with all of the other mods listed do not get disconnected on chat, but 1.19.1 which also has No Chat Reports does get disconnected like this.

I set my debugger to print every exception (caught or not), and besides all the `RunningOnDifferentThreadException`s nothing happens that could be triggering the disconnect, so it's probably server-side.

**Comment by LoganDark** [comment]
Yeah, Minecraft has no strings for "An internal error occurred in your connection". No Chat Reports is setting off some sort of server-side trigger, but I have no idea what it is. I don't think I'm equipped to investigate this any further.

(This is inside the dev environment BTW, with only No Chat Reports and AuthMe installed.)

**Comment by MODKILLER1001** [comment]
This could patch it possibly https://github.com/PaperMC/Velocity/commit/62bd58d356e9fd2b1f5ee25752ebdd455362798b

**Comment by LoganDark** [comment]
> This could patch it possibly [PaperMC/Velocity@62bd58d](https://github.com/PaperMC/Velocity/commit/62bd58d356e9fd2b1f5ee25752ebdd455362798b)

Yep that looks like the exact issue. The [error message comes from Velocity](https://github.com/PaperMC/Velocity/blob/d97ed956a7be1411b192939abcab8412932230b8/proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages.properties#L27). Thank you!

I've informed MineHut about the patch and I *hope* it makes it to their developers to get updated.

**Comment by Madis0** [comment]
Can confirm that the latest Velocity dev build fixes it, tested on a different server and asked them to update to latest build.

**Comment by Madis0** [comment]
Now this is confirmed to be fixed in MineHut as well.

**Comment by LoganDark** [comment]
If this is fixed on MineHut and upstream then I consider this issue solved, tyy

**Comment by Aizistral** [comment]
For future reference, I was informed that similar issue can occur when using SimplerAuth. Further verification is needed.
