### ISSUE TITLE
Incompatible mod set

### ISSUE THREAD

**Issue by giuliotoplad** [Aizistral-Studios/No-Chat-Reports#22]
![image](https://user-images.githubusercontent.com/36372281/176250550-af1cfdb8-59b9-48d5-8ab9-6202dd3d011c.png)

Minecraft Version: 1.19
Fabric Version: Fabric Loader 0.14.8
Java Version: Java SE Development Kit 17.0.3.1

Full Minecraft Log:
```log
[19:56:02] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[19:56:02] [main/WARN]: Mod resolution failed
[19:56:02] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE nochatreports 1.19-v1.2.2 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE nochatreports 1.19-v1.2.2]
[19:56:02] [main/INFO]: Reason: [HARD_DEP nochatreports 1.19-v1.2.2 {depends fabric @ [*]}]
[19:56:02] [main/INFO]: Fix: add [add:fabric 1 ([(-?,?)])], remove [], replace []
[19:56:02] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'No Chat Reports' (nochatreports) 1.19-v1.2.2 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1 (0x1).
```

**Comment by Aizistral** [comment]
You need to install Fabric API: https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by giuliotoplad** [comment]
> You need to install Fabric API: https://www.curseforge.com/minecraft/mc-mods/fabric-api

Ok, I installed Fabric API and now works, sorry for the inconvenience
