### ISSUE TITLE
Possible incompatibility with Polymer

### ISSUE THREAD

**Issue by kosma** [Aizistral-Studios/No-Chat-Reports#410]
### Modloader

Fabric

### Minecraft Version

1.20.1

### Modloader Version

0.14.21

### No Chat Reports Version

NoChatReports-FABRIC-1.20-v2.2.0.jar

### Bug Description

As discussed in Discord, I have found a potential incompatibility with Polymer when connecting with a vanilla client. The server says:

```
[02:48:37] [Netty Epoll Server IO #1/ERROR]: Received class net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket that couldn't be processed
java.lang.ClassCastException: class eu.pb4.polymer.networking.impl.PolymerHandshakeHandlerImplLogin cannot be cast to class net.minecraft.server.network.ServerPlayNetworkHandler (eu.pb4.p
olymer.networking.impl.PolymerHandshakeHandlerImplLogin and net.minecraft.server.network.ServerPlayNetworkHandler are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.Knot
ClassLoader @3c09711b)
        at net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.handler$bkl000$nochatreports$onHandle(PlayerSessionC2SPacket.java:525) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.apply(PlayerSessionC2SPacket.java) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.apply(PlayerSessionC2SPacket.java:7) ~[server-intermediary.jar:?]
        at net.minecraft.network.ClientConnection.handlePacket(ClientConnection.java:175) ~[server-intermediary.jar:?]
        at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:160) ~[server-intermediary.jar:?]
        at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:52) ~[server-intermediary.jar:?]
```

**Comment by elhertz** [comment]
Bumping this as I can't find an alternative for polymer and ncr

**Comment by ThatBlockyPenguin** [comment]
Bump again, just encountered this myself
