### ISSUE TITLE
Network errors, mixin errors in server log

### ISSUE THREAD

**Issue by allanonmage** [Aizistral-Studios/No-Chat-Reports#432]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

fabric-server-mc.1.19.2-loader.0.14.19-launcher.0.11.2.jar

### No Chat Reports Version

NoChatReports-FABRIC-1.19.2-v1.13.12.jar

### Bug Description

19:09:10] [Server thread/INFO]: Sending reload packet to clients
[19:48:51] [Netty Server IO #2/INFO]: Mixing common.MixinServerStatusSerializer from nochatreports.mixins.json into net.minecraft.class_2926$class_2929
[19:55:57] [Netty Server IO #3/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null
[19:59:10] [Netty Server IO #4/ERROR]: Exception occurred in netty pipeline
java.net.SocketException: Connection reset
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[netty-buffer-4.1.77.Final.jar:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.77.Final.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[20:07:35] [Netty Server IO #5/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null
[20:31:30] [Netty Server IO #6/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null

### Steps to Reproduce

I just installed the mod yesterday and I see these errors in the console.

### Other Information

All of my traffic goes through a VPN appliance, so is there some server that you're trying to reach that is blocking something because it comes from a VPN?

**Comment by Madis0** [comment]
Related to #418 

My guess is that NCR is not causing the errors in itself, but rather displaying the errors that you would not see otherwise. Have you tried it and can reproduce on newer Minecraft versions as well?

**Comment by Aizistral** [comment]
This doesn't look like NCR issue at all. The only line from an NCR mixin indicates that the mixin has loaded successfully. Further errors from Netty that occur below are not related to it, as evidenced by difference in time at which the lines were logged.
