### ISSUE TITLE
[NeoForge] 20.4.232 - Failed To Startup - Dedicated Server Crash

### ISSUE THREAD

**Issue by HalestormXV** [Aizistral-Studios/No-Chat-Reports#473]
### Modloader

Forge

### Minecraft Version

1.20.4

### Modloader Version

NeoForge 20.4.232

### No Chat Reports Version

NeForge-1.20.4-v2.6.0

### Modpack Info

https://modrinth.com/modpack/journey-beyond

### The latest.log File

https://mclo.gs/QIYPKyF

### Bug Description

Seems to be a crash relating to missing @SubscribeEvent methods but they are being called somewhere in the code anyway. Once you remove this mod Dedicated Server starts up no problem. Specifically here is the crash-log as well.  https://mclo.gs/LkG0AHX

### Steps to Reproduce

No real way to reproduce since the server fails to start.

**Comment by Aareon** [comment]
Same issue here. Log included

```log
[30Apr2024 11:10:00.668] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.neoForgeVersion, 20.4.234, --fml.fmlVersion, 2.0.17, --fml.mcVersion, 1.20.4, --fml.neoFormVersion, 20231207.154220]
[30Apr2024 11:10:00.674] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.10 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[30Apr2024 11:10:00.851] [main/INFO] [net.neoforged.fml.loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[30Apr2024 11:10:00.955] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/askul/AppData/Roaming/ATLauncher/servers/GOONCDF1204withNeoForge/libraries/net/fabricmc/sponge-mixin/0.13.1+mixin.0.8.5/sponge-mixin-0.13.1+mixin.0.8.5.jar%2379!/ Service=ModLauncher Env=SERVER
[30Apr2024 11:10:01.142] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "badpackets-neo-0.6.1.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.143] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "balm-neoforge-1.20.4-9.0.8.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.143] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "Chunky-1.3.136.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.144] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "ferritecore-6.0.3-forge.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.144] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "letmedespawn-neoforge-1.20.2-1.2.0.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.144] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "modernfix-neoforge-5.17.0+mc1.20.4.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.144] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "netherportalfix-neoforge-1.20.4-15.0.1.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.145] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "NoChatReports-NEOFORGE-1.20.4-v2.6.0.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.146] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "spark-1.10.61-neoforge.jar" of type MOD with provider {mods folder locator at C:\Users\askul\AppData\Roaming\ATLauncher\servers\GOONCDF1204withNeoForge\mods}
[30Apr2024 11:10:01.277] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "server-1.20.4-20231207.154220-srg.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@200a26bc
[30Apr2024 11:10:01.277] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "neoforge-20.4.234-universal.jar" of type MOD with provider net.neoforged.fml.loading.moddiscovery.MinecraftLocator@200a26bc
[30Apr2024 11:10:01.387] [main/INFO] [net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection
[30Apr2024 11:10:01.388] [main/INFO] [net.neoforged.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "mixinextras-neoforge-0.3.5.jar" of type GAMELIBRARY with provider net.neoforged.fml.loading.moddiscovery.JarInJarDependencyLocator@2b5cb9b2
[30Apr2024 11:10:02.957] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[30Apr2024 11:10:02.999] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[30Apr2024 11:10:03.221] [main/WARN] [mixin/]: Reference map 'badpackets.refmap.json' for badpackets.mixins.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.223] [main/WARN] [mixin/]: Reference map 'netherportalfix.refmap.json' for netherportalfix.mixins.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.226] [main/WARN] [mixin/]: Reference map 'letmedespawn.refmap.json' for letmedespawn.mixins.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.228] [main/WARN] [mixin/]: Reference map 'nochatreports.refmap.json' for mixins/common/nochatreports.mixins.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.265] [main/WARN] [mixin/]: Reference map 'ferritecore.refmap.json' for ferritecore.predicates.mixin.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.267] [main/WARN] [mixin/]: Reference map 'ferritecore.refmap.json' for ferritecore.fastmap.mixin.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.269] [main/WARN] [mixin/]: Reference map 'ferritecore.refmap.json' for ferritecore.mrl.mixin.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.271] [main/WARN] [mixin/]: Reference map 'ferritecore.refmap.json' for ferritecore.dedupmultipart.mixin.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.274] [main/WARN] [mixin/]: Reference map 'ferritecore.refmap.json' for ferritecore.blockstatecache.mixin.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.276] [main/WARN] [mixin/]: Reference map 'ferritecore.refmap.json' for ferritecore.dedupbakedquad.mixin.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.278] [main/WARN] [mixin/]: Reference map 'ferritecore.refmap.json' for ferritecore.threaddetec.mixin.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.280] [main/WARN] [mixin/]: Reference map 'ferritecore.refmap.json' for ferritecore.modelsides.mixin.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:03.455] [main/INFO] [ModernFix/]: Loaded configuration file for ModernFix 5.17.0+mc1.20.4: 67 options available, 0 override(s) found
[30Apr2024 11:10:03.457] [main/INFO] [ModernFix/]: Applying Nashorn fix
[30Apr2024 11:10:03.481] [main/INFO] [ModernFix/]: Applied Forge config corruption patch
[30Apr2024 11:10:03.487] [main/WARN] [mixin/]: Reference map 'balm.refmap.json' for balm.mixins.json could not be read. If this is a development environment you can ignore this message
[30Apr2024 11:10:04.062] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[30Apr2024 11:10:05.474] [main/INFO] [net.minecraft.server.Bootstrap/]: ModernFix reached bootstrap stage (7.345 s after launch)
[30Apr2024 11:10:09.732] [main/INFO] [net.minecraft.server.Bootstrap/]: Vanilla bootstrap took 4254 milliseconds
[30Apr2024 11:10:09.881] [modloading-worker-0/INFO] [net.neoforged.neoforge.common.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 20.4.234, for MC 1.20.4 with MCP 20231207.154220
[30Apr2024 11:10:09.911] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: nochatreports, class com.aizistral.nochatreports.neoforge.NoChatReports
java.lang.IllegalArgumentException: class com.aizistral.nochatreports.neoforge.NoChatReports$Events has no @SubscribeEvent methods, but register was called anyway.
The event bus only recognizes listener methods that have the @SubscribeEvent annotation.

	at net.neoforged.bus.EventBus.register(EventBus.java:115) ~[bus-7.2.0.jar%2370!/:?]
	at net.neoforged.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:70) ~[loader-2.0.17.jar%2362!/:2.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.neoforged.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:50) ~[loader-2.0.17.jar%2362!/:2.0]
	at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:123) ~[loader-2.0.17.jar%2362!/:2.0]
	at net.neoforged.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:129) ~[loader-2.0.17.jar%2362!/:2.0]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[30Apr2024 11:10:10.353] [main/FATAL] [net.neoforged.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[30Apr2024 11:10:10.493] [main/ERROR] [net.minecraft.CrashReport/]: Negative index in crash report handler (19/21)
[30Apr2024 11:10:10.509] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 5b4c5ab7-83e3-4992-a1a6-1a6d75b66c33
[30Apr2024 11:10:10.510] [main/FATAL] [net.neoforged.neoforge.server.loading.ServerModLoader/]: Crash report saved to .\crash-reports\crash-2024-04-30_11.10.10-fml.txt
[30Apr2024 11:10:10.512] [main/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID b45f130f-cb6e-47a5-9040-d0f8db81aed9
[30Apr2024 11:10:10.516] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.neoforged.fml.LoadingFailedException: Loading errors encountered: [
	No Chat Reports (nochatreports) has failed to load correctly
§7java.lang.IllegalArgumentException: class com.aizistral.nochatreports.neoforge.NoChatReports$Events has no @SubscribeEvent methods, but register was called anyway.
The event bus only recognizes listener methods that have the @SubscribeEvent annotation.

]
	at net.neoforged.fml.ModLoader.waitForTransition(ModLoader.java:254) ~[loader-2.0.17.jar%2362!/:2.0]
	at net.neoforged.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:218) ~[loader-2.0.17.jar%2362!/:2.0]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.neoforged.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[loader-2.0.17.jar%2362!/:2.0]
	at net.neoforged.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:191) ~[loader-2.0.17.jar%2362!/:2.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[loader-2.0.17.jar%2362!/:2.0]
	at net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[neoforge-20.4.234-universal.jar%23143!/:?]
	at net.minecraft.server.Main.main(Main.java:122) ~[server-1.20.4-20231207.154220-srg.jar%23142!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar%2362!/:2.0]
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-2.0.17.jar%2362!/:2.0]
	at net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:26) ~[loader-2.0.17.jar%2362!/:2.0]
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar%2362!/:2.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2365!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2365!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2365!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2365!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2365!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2365!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2365!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```
