### ISSUE TITLE
Network protocol error in accessing Spigot server

### ISSUE THREAD

**Issue by shotadft** [Aizistral-Studios/No-Chat-Reports#492]
### Modloader

Fabric

### Minecraft Version

1.21.1

### Modloader Version

Loader 0.16.7

### No Chat Reports Version

fabric-2.9.0

### The latest.log File

See Other Information

### Bug Description

Attempting to connect to a Spigot server causes a network protocol error and fails to connect to the server.

### Steps to Reproduce

1. Access to spigot server
2. Crash

### Other Information

Crash Log:
```log
---- Minecraft Network Protocol Error Report ----
// Could be worse, I guess

Time: 2024-10-29 21:11:04
Description: Packet handling error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_30349()" because "this.field_2062.field_1687" is null
	at knot//net.minecraft.class_338.localvar$ekd000$nochatreports$modifyGUIMessage(class_338.java:2629)
	at knot//net.minecraft.class_338.method_44811(class_338.java:213)
	at knot//net.minecraft.class_338.method_1812(class_338.java:208)
	at knot//net.minecraft.class_7594.method_44736(class_7594.java:196)
	at knot//net.minecraft.class_634.method_43596(class_634.java:904)
	at knot//net.minecraft.class_7439.method_43631(class_7439.java:25)
	at knot//net.minecraft.class_7439.method_11054(class_7439.java:11)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
```

**Comment by Onako2** [comment]
Hi!
Does it also happen when you join a Paper server?

**Comment by shotadft** [comment]
No, this is happening only on Spigot servers.

**Comment by Onako2** [comment]
Couldn't reproduce issue on Minecraft 1.21.1 Fabric and 1.21.1 Spigot (4344) Server.  
Could you provide more informtion on your configuration of No Chat Reports.

Also could you please upload **full** logs of client and server on https://mclo.gs/ and send the link of both logs here

**Comment by Onako2** [comment]
Haha now I also have the error!

Could also be because of other mods 🤔 
https://mclo.gs/0BOmtKN

**Comment by shotadft** [comment]
Maybe: Noxesium

**Comment by REALERvolker1** [comment]
Can confirm this happens with me as well, when connecting to servers like `thearchive.world`

**Comment by itsTyrion** [comment]
I have it on a Paper server, but not always, and usually when switching between the different servers behind Velocity.
I'll investigate.

**Comment by itsTyrion** [comment]
I think it's related to permissions/operator:

When trying to connect with * permissions (=- operator, since LuckPerms does that automatically), the error occurs 100% of the time. 

When using my alt account that has no special perms, I can't reproduce it.

When using my admin account the usual way (connect with no perms, type 2FA code, get * permission from plugin, switch to hub server), the error occurs 100% when switching servers (verify -> hub/verify -> survival/etc.)

I cannot reproduce it with 2.8.0 of NCR however, only 2.9.0

**Comment by Thijzert123** [comment]
Yup, also happens to me 100% of the time on my own personal paper server... (I also have Velocity)

**Comment by Thijzert123** [comment]
Also, as reported on #493, maybe via version is part of the problem?

**Comment by shotadft** [comment]
ok, thx.

**Comment by shotadft** [comment]
As a matter of fact, the server I tried to connect to did not have anything like Luckperms, but it did have ViaVersion. This is probably a duplicate or similar bug to #493.

**Comment by Thijzert123** [comment]
Yeah... It's unfortunate that disabling the mod doesn't resolve the issue, at least not in my case. I have to remove the mod entirely

**Comment by itsTyrion** [comment]
I cannot reproduce the issue with 2.8.0 or without having admin perms on the server so try using 2.8.0 for now

**Comment by Thijzert123** [comment]
I also tried it and it worked for me, thanks!

**Comment by Madis0** [comment]
Can confirm with the server posted to #494, even with the NCR "enable mod" is set to OFF.

**Comment by shotadft** [comment]
I didn't know they reported so many...
**Any fixes yet?**
