### ISSUE TITLE
Could not retrieve profile key pair

### ISSUE THREAD

**Issue by Intaria** [Aizistral-Studios/No-Chat-Reports#498]
### Modloader

Forge

### Minecraft Version

1.19.2

### Modloader Version

FORGE-1.19.2-43.3.7

### No Chat Reports Version

FORGE-1.19.2-v1.5.1

### Bug Description

```
[22дек.2024 02:06:46.166] [Render thread/INFO] [mixin/]: Mixing client.MixinProfileKeyPairManager from nochatreports.mixins.json into net.minecraft.client.multiplayer.ProfileKeyPairManager
[22дек.2024 02:06:46.190] [Worker-Main2/ERROR] [net.minecraft.client.multiplayer.ProfileKeyPairManager/]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at net.minecraft.client.multiplayer.ProfileKeyPairManager.m_233789_(ProfileKeyPairManager.java:152) ~[client-1.19.2-20220805.130853-srg.jar%23523!/:?]
	at net.minecraft.client.multiplayer.ProfileKeyPairManager.m_243396_(ProfileKeyPairManager.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23523!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[22дек.2024 02:06:46.190] [Render thread/INFO] [mixin/]: Mixing client.MixinChatListener from nochatreports.mixins.json into net.minecraft.client.multiplayer.chat.ChatListener
```

**Comment by Madis0** [comment]
Cannot confirm, probably a launcher bug. Try a different launcher, such as Prism Launcher.
