### ISSUE TITLE
Error: "Incompatible mod set!" w/ Fabric for 1.19 and NoChatReports-FABRIC-1.19-v1.2.3.jar

### ISSUE THREAD

**Issue by Taurxs** [Aizistral-Studios/No-Chat-Reports#85]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'No Chat Reports' (nochatreports) 1.19-v1.2.0 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Aizistral** [comment]
You forgot to install Fabric API. Notice that it is something that comes packaged as mod, you have to install it separately from Fabric loader: https://www.curseforge.com/minecraft/mc-mods/fabric-api
